spring:
    application:
        name: yogihr
    datasource:
        url: jdbc:mysql://localhost:3306/employee
        username: root
        password: password
logging:
    level:
        org:
            springframework:
                jdbc:
                    core: TRACE


# Lists of values to ensure validation and database integrity
states: AL, AK, AZ, AR, CA, CO, CT, DE, FL, GA, HI, ID, IL, IN, IA, KS, KY, LA, ME, MD, MA, MI, MN, MS, MO, MT, NE, NV, NH, NJ, NM, NY, NC, ND, OH, OK, OR, PA, RI, SC, SD, TN, TX, UT, VT, VA, WA, WV, WI, WY
emp_types: W2, 1099
pay_types: Hourly, Salary
pay_frequencies: Bi-Weekly, Weekly
dol_statuses: Full-Time, Part-Time
genders: M, F